/* AUTOGENERATED DO NOT MODIFY */

/**
  ******************************************************************************
  * @file    tof_module_v3.c
  * @brief   NN Code autogenerated DO NOT MODIFY IT
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2023 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

/*
 * GIT_SHA         "27f5d5bcb9ca9522b73a54d7aec841664ee448cd"
 * GIT_BRANCH      "STAI-2.1"
 * GIT_DESCRIPTION "atonn-v1.1.0-31-g27f5d5bcb"
 *
 * Command Line options:
 * --onnx-input = "C:/Users/lenovo/.stm32cubemx/tof_module_v3_output/tof_model_quant_random_2_OE_3_2_0.onnx"
 * --out-dir-prefix = "C:/Users/lenovo/AppData/Local/Temp/mxAI_workspace1103197431439001478323714346931970/neural_art__tof_module_v3/"
 * --network-name = "tof_module_v3"
 * --all-buffers-info = true
 * --mvei = true
 * --load-mdesc-file = "D:/StEdgeAI/2.1/Utilities/configs/stm32n6"
 * --load-mpool-file = "D:/StEdgeAI/2.1/scripts/N6_scripts/my_mpools/stm32n6tof"
 * --cache-maintenance = true
 * --enable-virtual-mem-pools = true
 * --native-float = true
 * --json-quant-file = "C:/Users/lenovo/.stm32cubemx/tof_module_v3_output/tof_model_quant_random_2_OE_3_2_0_Q.json"
 * --Os = true
 * --Omax-ca-pipe = 4
 * --Ocache-opt = true
 * --output-info-file = "c_info"
 * --Oauto-sched = true
 *
 * auto* option expanded into:
 *   alt-scheduler = false
 */

#include "ll_aton_NN_interface.h"
#include "ll_aton.h"
#include "ll_aton_lib.h"
#include "ll_aton_version.h"
#include "ll_sw.h"

#if LL_ATON_VERSION_MAJOR != 1 || LL_ATON_VERSION_MINOR != 1 || LL_ATON_VERSION_MICRO != 0 || LL_ATON_VERSION_DEV != 31
#  warning "Possible mismatch in ll_aton library used"
#endif

#if !defined(LL_ATON_DBG_BUFFER_INFO_EXCLUDED)
#  define LL_ATON_DBG_BUFFER_INFO_EXCLUDED 0
#endif

/* global pool 7 is ? */
/* index=7 file postfix=xSPI1 name=hyperRAM offset=0x90000000  absolute_mode size=33554424 READ_WRITE THROUGHPUT=MID LATENCY=HIGH byte width=2 freq ratio=5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=ON read_power=380 write_power=340 use4initializers=YES score=82  */
/* global pool 8 is 5.58 KB */
/* index=8 file postfix=xSPI2 name=octoFlash offset=0x71000000  absolute_mode size=1048568 READ_ONLY THROUGHPUT=MID LATENCY=HIGH byte width=1 freq ratio=6 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=ON read_power=110 write_power=400 use4initializers=YES score=50  */
/* global pool 1 is 384 B */
/* index=1 file postfix=AXISRAM5 name=npuRAM5 offset=0x342e0000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 2 is ? */
/* index=2 file postfix=AXISRAM4 name=npuRAM4 offset=0x34270000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 3 is ? */
/* index=3 file postfix=AXISRAM3 name=npuRAM3 offset=0x34200000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 0 is ? */
/* index=0 file postfix=AXISRAM6 name=npuRAM6 offset=0x34350000  absolute_mode size=458744 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=19.006 write_power=15.79 use4initializers=NO score=94  */
/* global pool 11 is 1.88 MB */
/* index=11 file postfix=AXISRAM2_AXISRAM3_AXISRAM4_AXISRAM5_AXISRAM6 name=cpuRAM2_npuRAM3_npuRAM4_npuRAM5_npuRAM6 offset=0x34100000  absolute_mode size=2883576 vpool READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=19.006 write_power=16.201 use4initializers=NO score=85  */
/* global pool 4 is ? */
/* index=4 file postfix=AXISRAM2 name=cpuRAM2 offset=0x34100000  absolute_mode size=1048576 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=17.324 write_power=15.321 use4initializers=NO score=84  */
/* global pool 5 is ? */
/* index=5 file postfix=AXISRAM1 name=cpuRAM1 offset=0x34064000  absolute_mode size=0 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=16.616 write_power=14.522 use4initializers=NO score=84  */
/* global pool 6 is ? */
/* index=6 file postfix=AXIFLEXMEM name=flexMEM offset=0x34000000  absolute_mode size=0 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=9.381 write_power=8.569 use4initializers=NO score=84  */

LL_ATON_User_IO_Result_t LL_ATON_Set_User_Input_Buffer_tof_module_v3(uint32_t num, void* buffer, uint32_t size)
{
  { 
    return LL_ATON_User_IO_WRONG_INDEX;
  }
}

void *LL_ATON_Get_User_Input_Buffer_tof_module_v3(uint32_t num)
{
  { 
    return NULL;
  }
}

LL_ATON_User_IO_Result_t LL_ATON_Set_User_Output_Buffer_tof_module_v3(uint32_t num, void* buffer, uint32_t size)
{
  { 
    return LL_ATON_User_IO_WRONG_INDEX;
  }
}

void *LL_ATON_Get_User_Output_Buffer_tof_module_v3(uint32_t num)
{
  { 
    return NULL;
  }
}

bool LL_ATON_EC_Network_Init_tof_module_v3(void)
{
  return true;
}

bool LL_ATON_EC_Inference_Init_tof_module_v3(void)
{
  return true;
}

/* scheduling epoch=0    nodes=13  ------------------------------------------------------------------- */

/* scheduling epoch=1    nodes=1   ------------------------------------------------------------------- */

static void LL_ATON_Start_EpochBlock_1(const void *epoch_block)
{
  LL_ATON_LIB_UNUSED(epoch_block);

  /* Unit= 18 [ARITH_ACC_V2 0] */
  /* kind=Sub node=Conv2D_4_suboff_6 */
  static const LL_Arithacc_InitTypeDef Conv2D_4_suboff_6_init1 = {
    .rounding_x = 0,
    .saturation_x = 0,
    .round_mode_x = 0,
    .inbytes_x = 1,
    .outbytes_x = 1,
    .shift_x = 0,
    .rounding_y = 0,
    .saturation_y = 0,
    .round_mode_y = 0,
    .inbytes_y = 1,
    .outbytes_y = 1,
    .combinebc = 1,
    .clipout = 0,
    .shift_y = 0,
    .rounding_o = 0,
    .saturation_o = 0,
    .round_mode_o = 1,
    .relu_mode_o = 0,
    .outbytes_o = 1,
    .shift_o = 14,
    .scalar = 1,
    .dualinput = 0,
    .operation = ARITH_AFFINE,
    .bcast = ARITH_BCAST_CHAN,
    .Ax_shift = 0,
    .By_shift = 0,
    .C_shift = 0,
    .fWidth = 8,
    .fHeight = 8,
    .fChannels = 1,
    .batchDepth = 1,
    .clipmin = 0,
    .clipmax = 0,
    .A_scalar = 16384,
    .B_scalar = 32,
    .C_scalar = (short)0,
    .A_vector = {0},
    .B_vector = {0},
    .C_vector = {0},
    .vec_precision = {8, 8, 8},
  };

  /* Unit=ARITH_ACC_V2 */
  LL_Arithacc_Init(0, &Conv2D_4_suboff_6_init1);


  /* Dma inputs units to cycle: */
  /* Unit= 9 [STREAM_ENG_V2 9] */
  /* Emit conf for STREAM_ENG_V2 node=Conv2D_4_suboff_6 input ports=0 range=1[0,64] */

  static const LL_Streng_TensorInitTypeDef Conv2D_4_suboff_6_dma_init_in_0_1 = {
    /* from memory with batch=1 */
    .dir = 0,
    .raw = 1,
    .noblk = 0,
    .align_right = 0,
    .nbits_unsigned = 0,
    .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */}, /* Dequantize_3_out_0 */
    .offset_start = 0,
    .offset_end = 64,
    .offset_limit = 128,
    .frame_count = 0,
    .fwidth = 0,
    .fheight = 0,
    .batch_depth = 0,
    .batch_offset = 0,
    .frame_offset = 64,
    .line_offset = 0,
    .loop_offset = 0,
    .frame_loop_cnt = 0,
    .frame_tot_cnt = 1,
    .nbits_in = 8,
    .nbits_out = 8,
  };

  /* Unit=STREAM_ENG_V2 */
  LL_Streng_TensorInit(9, &Conv2D_4_suboff_6_dma_init_in_0_1, 1);


  /* Dma input bandwidth from memory pools: */
  /* npuRAM5 -> 64 */

  /* Dma output units from cycle: */
  /* Unit= 4 [STREAM_ENG_V2 4] */
  /* Emit conf for STREAM_ENG_V2 node=Conv2D_4_suboff_6 output ports=0 range=1[256,320] */

  static const LL_Streng_TensorInitTypeDef Conv2D_4_suboff_6_dma_init_out_0_1 = {
    /* to memory with batch=1 */
    .dir = 1,
    .raw = 1,
    .noblk = 0,
    .align_right = 0,
    .nbits_unsigned = 1,
    .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */}, /* Conv2D_4_zero_off_out_7 */
    .offset_start = 256,
    .offset_end = 320,
    .offset_limit = 384,
    .frame_count = 0,
    .fwidth = 0,
    .fheight = 0,
    .batch_depth = 0,
    .batch_offset = 0,
    .frame_offset = 64,
    .line_offset = 0,
    .loop_offset = 0,
    .frame_loop_cnt = 0,
    .frame_tot_cnt = 1,
    .nbits_in = 8,
    .nbits_out = 8,
  };

  /* Unit=STREAM_ENG_V2 */
  LL_Streng_TensorInit(4, &Conv2D_4_suboff_6_dma_init_out_0_1, 1);


  /* Dma output bandwidth to memory pools: */
  /* npuRAM5 <- 64 */

  static const LL_Switch_InitTypeDef switch_init_in_1[] = {
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, ARITH, 0, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 9, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_4_suboff_6 IN: in unit=ARITH_ACC_V2 0 in port=0 out unit=STREAM_ENG_V2 9 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, STRENG, 4, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, ARITH, 0, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_4_suboff_6 OUT: in unit=STREAM_ENG_V2 4 in port=0 out unit=ARITH_ACC_V2 0 out port=0 */
  };


  /* epoch=1 */
  LL_Switch_Init(switch_init_in_1, 2);

  static const LL_ATON_EnableUnits_InitTypeDef Enable_epoch_1_all_units[] = {
    { {STRENG, 4} }, /* STREAM_ENG_V2 */
    { {ARITH, 0} }, /* ARITH_ACC_V2 */
    { {STRENG, 9} }, /* STREAM_ENG_V2 */
  };


  LL_ATON_EnableUnits_Init(Enable_epoch_1_all_units, 3);

}

static void LL_ATON_End_EpochBlock_1(const void *epoch_block)
{
  LL_ATON_LIB_UNUSED(epoch_block);

  static const LL_Switch_DeinitTypeDef switch_deinit_in_1[] = {
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, ARITH, 0, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 9, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_4_suboff_6 IN: in unit=ARITH_ACC_V2 0 in port=0 out unit=STREAM_ENG_V2 9 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, STRENG, 4, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, ARITH, 0, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_4_suboff_6 OUT: in unit=STREAM_ENG_V2 4 in port=0 out unit=ARITH_ACC_V2 0 out port=0 */
  };


  /* epoch=1 */
  LL_Switch_Deinit(switch_deinit_in_1, 2);

  static const LL_ATON_DisableUnits_InitTypeDef Disable_epoch_1_all_units[] = {
    { {STRENG, 4} }, /* STREAM_ENG_V2 */
    { {ARITH, 0} }, /* ARITH_ACC_V2 */
    { {STRENG, 9} }, /* STREAM_ENG_V2 */
  };


  LL_ATON_DisableUnits_Init(Disable_epoch_1_all_units, 3);

}


/* scheduling epoch=2    nodes=5   ------------------------------------------------------------------- */

static void LL_ATON_Start_EpochBlock_2(const void *epoch_block)
{
  LL_ATON_LIB_UNUSED(epoch_block);

  /* Unit= 10 [CONV_ACC_V2 0] */
  /* kind=Conv node=Conv2D_4 */
  static const LL_Convacc_InitTypeDef Conv2D_4_init2 = {
    .simd = 1,
    .fsub = 0,
    .accumulate = 0,
    .rounding_f = 0,
    .saturation_f = 0,
    .round_mode_f = 0,
    .f_unsigned = 1,
    .k_unsigned = 0,
    .deepmode = 0,
    .dss2mode = 0,
    .kseten = 0,
    .zfbias = 0,
    .inbytes_f = 1,
    .shift_f = 0,
    .shift_a = 1,
    .rounding_o = 1,
    .saturation_o = 1,
    .round_mode_o = 1,
    .relu_mode_o = 0,
    .outbytes_o = 2,
    .shift_o = 1,
    .raw_o = 0,
    .fWidth = 8,
    .fHeight = 8,
    .kernelWidth = 3,
    .kernelHeight = 3,
    .nKernels = 8,
    .batchDepth = 1,
    .hstride = 1,
    .vstride = 1,
    .left_padding = 1,
    .right_padding = 1,
    .top_padding = 1,
    .bot_padding = 1,
    .left_crop = 0,
    .right_crop = 7,
    .top_crop = 0,
    .bot_crop = 7,
  };

  /* Unit=CONV_ACC_V2 */
  LL_Convacc_Init(0, &Conv2D_4_init2);


  /* Unit= 19 [ARITH_ACC_V2 1] */
  /* kind=Mul node=Conv2D_4_mul_scale_9 */
  static const LL_Arithacc_InitTypeDef Conv2D_4_mul_scale_9_init2 = {
    .rounding_x = 0,
    .saturation_x = 0,
    .round_mode_x = 0,
    .inbytes_x = 2,
    .outbytes_x = 2,
    .shift_x = 0,
    .rounding_y = 0,
    .saturation_y = 0,
    .round_mode_y = 0,
    .inbytes_y = 2,
    .outbytes_y = 2,
    .combinebc = 0,
    .clipout = 0,
    .shift_y = 0,
    .rounding_o = 1,
    .saturation_o = 1,
    .round_mode_o = 1,
    .relu_mode_o = 0,
    .outbytes_o = 2,
    .shift_o = 16,
    .scalar = 1,
    .dualinput = 0,
    .operation = ARITH_AFFINE,
    .bcast = ARITH_BCAST_SCALAR,
    .Ax_shift = 0,
    .By_shift = 0,
    .C_shift = 0,
    .fWidth = 8,
    .fHeight = 8,
    .fChannels = 16,
    .batchDepth = 8,
    .clipmin = 0,
    .clipmax = 0,
    .A_scalar = 30695,
    .B_scalar = 0,
    .C_scalar = 0,
    .A_vector = {0},
    .B_vector = {0},
    .C_vector = {0},
    .vec_precision = {16, 16, 16},
  };

  /* Unit=ARITH_ACC_V2 */
  LL_Arithacc_Init(1, &Conv2D_4_mul_scale_9_init2);


  /* Unit= 20 [ARITH_ACC_V2 2] */
  /* kind=Add node=Conv2D_4_off_bias_12 */
  static const LL_Arithacc_InitTypeDef Conv2D_4_off_bias_12_init2 = {
    .rounding_x = 0,
    .saturation_x = 0,
    .round_mode_x = 0,
    .inbytes_x = 2,
    .outbytes_x = 2,
    .shift_x = 0,
    .rounding_y = 0,
    .saturation_y = 0,
    .round_mode_y = 0,
    .inbytes_y = 2,
    .outbytes_y = 2,
    .combinebc = 1,
    .clipout = 0,
    .shift_y = 0,
    .rounding_o = 1,
    .saturation_o = 1,
    .round_mode_o = 1,
    .relu_mode_o = 0,
    .outbytes_o = 1,
    .shift_o = 20,
    .scalar = 0,
    .dualinput = 0,
    .operation = ARITH_AFFINE,
    .bcast = ARITH_BCAST_CHAN,
    .Ax_shift = 0,
    .By_shift = 0,
    .C_shift = 0,
    .fWidth = 8,
    .fHeight = 8,
    .fChannels = 16,
    .batchDepth = 8,
    .clipmin = 0,
    .clipmax = 0,
    .A_scalar = 21695,
    .B_scalar = 0,
    .C_scalar = (short)0,
    .A_vector = {0},
    .B_vector = {0},
    .C_vector = {((unsigned char *)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x71000000UL + 5536))) /* Equivalent hex address = 0x710015a0UL */},
    .vec_precision = {16, 16, 32},
  };

  /* Unit=ARITH_ACC_V2 */
  LL_Arithacc_Init(2, &Conv2D_4_off_bias_12_init2);


  /* Unit= 22 [POOL_ACC_V2 0] */
  /* kind=MaxPool node=MaxPool_7 */
  static const LL_Poolacc_InitTypeDef MaxPool_7_init2 = {
    .operation = POOL_MAX,
    .avgnopad = 0,
    .inputX = 8,
    .inputY = 8,
    .outputX = 4,
    .outputY = 4,
    .poolWinX = 2,
    .poolWinY = 2,
    .strideX = 2,
    .strideY = 2,
    .topCrop = 0,
    .bottomCrop = 7,
    .leftCrop = 0,
    .rightCrop = 7,
    .topPad = 0,
    .bottomPad = 0,
    .leftPad = 0,
    .rightPad = 0,
    .batchSize = 8,
    .shift_f = 0,
    .shift_o = 0,
    .dualLine = 1,
    .rounding_f = 0,
    .saturation_f = 0,
    .round_mode_f = 0,
    .inbytes_f = 1,
    .outbytes_f = 1,
    .rounding_o = 1,
    .saturation_o = 1,
    .round_mode_o = 1,
    .relu_mode_o = 0,
    .outbytes_o = 1,
    .mulval = 0,
    .pad_val_en = 0,
    .pad_val = 0,
  };

  /* Unit=POOL_ACC_V2 */
  LL_Poolacc_Init(0, &MaxPool_7_init2);


  /* Unit= 21 [ARITH_ACC_V2 3] */
  /* kind=Sub node=Conv2D_8_suboff_15 */
  static const LL_Arithacc_InitTypeDef Conv2D_8_suboff_15_init2 = {
    .rounding_x = 0,
    .saturation_x = 0,
    .round_mode_x = 0,
    .inbytes_x = 1,
    .outbytes_x = 1,
    .shift_x = 0,
    .rounding_y = 0,
    .saturation_y = 0,
    .round_mode_y = 0,
    .inbytes_y = 1,
    .outbytes_y = 1,
    .combinebc = 1,
    .clipout = 0,
    .shift_y = 0,
    .rounding_o = 0,
    .saturation_o = 0,
    .round_mode_o = 1,
    .relu_mode_o = 0,
    .outbytes_o = 1,
    .shift_o = 14,
    .scalar = 1,
    .dualinput = 0,
    .operation = ARITH_AFFINE,
    .bcast = ARITH_BCAST_SCALAR,
    .Ax_shift = 0,
    .By_shift = 0,
    .C_shift = 0,
    .fWidth = 4,
    .fHeight = 4,
    .fChannels = 16,
    .batchDepth = 8,
    .clipmin = 0,
    .clipmax = 0,
    .A_scalar = 16384,
    .B_scalar = 32,
    .C_scalar = (short)0,
    .A_vector = {0},
    .B_vector = {0},
    .C_vector = {0},
    .vec_precision = {8, 8, 8},
  };

  /* Unit=ARITH_ACC_V2 */
  LL_Arithacc_Init(3, &Conv2D_8_suboff_15_init2);


  /* Dma inputs units to cycle: */
  /* Unit= 0 [STREAM_ENG_V2 0] */
  /* Emit conf for STREAM_ENG_V2 node=Conv2D_4 input ports=0 range=1[256,320] */

  static const LL_Streng_TensorInitTypeDef Conv2D_4_dma_init_in_0_2 = {
    /* 8x8x1(8 bits) */
    .dir = 0,
    .raw = 1,
    .noblk = 0,
    .align_right = 0,
    .nbits_unsigned = 1,
    .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */}, /* Conv2D_4_zero_off_out_7 */
    .offset_start = 256,
    .offset_end = 320,
    .offset_limit = 384,
    .frame_count = 0,
    .fwidth = 0,
    .fheight = 0,
    .batch_depth = 0,
    .batch_offset = 0,
    .frame_offset = 64,
    .line_offset = 0,
    .loop_offset = 0,
    .frame_loop_cnt = 1,
    .frame_tot_cnt = 2,
    .nbits_in = 8,
    .nbits_out = 8,
  };

  /* Unit=STREAM_ENG_V2 */
  LL_Streng_TensorInit(0, &Conv2D_4_dma_init_in_0_2, 1);

  /* Unit= 3 [STREAM_ENG_V2 3] */
  /* Emit conf for STREAM_ENG_V2 node=Conv2D_4 input ports=1 range=8[5264,5408] */

  static const LL_Streng_TensorInitTypeDef Conv2D_4_dma_init_in_1_2 = {
    /* 16x3x3x1(8 bits) */
    .dir = 0,
    .raw = 1,
    .continuous = 1,
    .noblk = 0,
    .align_right = 0,
    .nbits_unsigned = 0,
    .cacheable = 1,
    .cache_allocate = 0,
    .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */}, /* Conv2D_4_weights */
    .offset_start = 5264,
    .offset_end = 5408,
    .offset_limit = 5472,
    .frame_count = 0,
    .fwidth = 0,
    .fheight = 0,
    .batch_depth = 0,
    .batch_offset = 0,
    .frame_offset = 0,
    .line_offset = 0,
    .loop_offset = 0,
    .frame_loop_cnt = 0,
    .frame_tot_cnt = 1,
    .nbits_in = 8,
    .nbits_out = 8,
  };

  /* Unit=STREAM_ENG_V2 */
  LL_Streng_TensorInit(3, &Conv2D_4_dma_init_in_1_2, 1);


  /* Dma input bandwidth from memory pools: */
  /* npuRAM5 -> 64 */
  /* octoFlash -> 144 */

  /* Dma output units from cycle: */
  /* Unit= 7 [STREAM_ENG_V2 7] */
  /* Emit conf for STREAM_ENG_V2 node=Conv2D_8_suboff_15 output ports=0 range=1[0,256] */

  static const LL_Streng_TensorInitTypeDef Conv2D_8_suboff_15_dma_init_out_0_2 = {
    /* to memory with batch=8 */
    .dir = 1,
    .raw = 1,
    .noblk = 0,
    .align_right = 0,
    .nbits_unsigned = 1,
    .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */}, /* Conv2D_8_zero_off_out_16 */
    .offset_start = 0,
    .offset_end = 128,
    .offset_limit = 320,
    .frame_count = 0,
    .fwidth = 0,
    .fheight = 0,
    .batch_depth = 0,
    .batch_offset = 0,
    .frame_offset = 128,
    .line_offset = 0,
    .loop_offset = 0,
    .frame_loop_cnt = 0,
    .frame_tot_cnt = 2,
    .nbits_in = 8,
    .nbits_out = 8,
  };

  /* Unit=STREAM_ENG_V2 */
  LL_Streng_TensorInit(7, &Conv2D_8_suboff_15_dma_init_out_0_2, 1);


  /* Dma output bandwidth to memory pools: */
  /* npuRAM5 <- 256 */

  static const LL_Switch_InitTypeDef switch_init_in_2[] = {
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, CONVACC, 0, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 0, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_4 IN: in unit=CONV_ACC_V2 0 in port=0 out unit=STREAM_ENG_V2 0 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, CONVACC, 0, 1), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 3, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_4 IN: in unit=CONV_ACC_V2 0 in port=1 out unit=STREAM_ENG_V2 3 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, ARITH, 1, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, CONVACC, 0, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_4_mul_scale_9 IN: in unit=ARITH_ACC_V2 1 in port=0 out unit=CONV_ACC_V2 0 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, ARITH, 2, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, ARITH, 1, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_4_off_bias_12 IN: in unit=ARITH_ACC_V2 2 in port=0 out unit=ARITH_ACC_V2 1 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, POOL, 0, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, ARITH, 2, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* MaxPool_7 IN: in unit=POOL_ACC_V2 0 in port=0 out unit=ARITH_ACC_V2 2 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, ARITH, 3, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, POOL, 0, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_8_suboff_15 IN: in unit=ARITH_ACC_V2 3 in port=0 out unit=POOL_ACC_V2 0 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, STRENG, 7, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, ARITH, 3, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_8_suboff_15 OUT: in unit=STREAM_ENG_V2 7 in port=0 out unit=ARITH_ACC_V2 3 out port=0 */
  };


  /* epoch=2 */
  LL_Switch_Init(switch_init_in_2, 7);

  static const LL_ATON_EnableUnits_InitTypeDef Enable_epoch_2_all_units[] = {
    { {STRENG, 7} }, /* STREAM_ENG_V2 */
    { {CONVACC, 0} }, /* CONV_ACC_V2 */
    { {ARITH, 1} }, /* ARITH_ACC_V2 */
    { {ARITH, 2} }, /* ARITH_ACC_V2 */
    { {ARITH, 3} }, /* ARITH_ACC_V2 */
    { {POOL, 0} }, /* POOL_ACC_V2 */
    { {STRENG, 0} }, /* STREAM_ENG_V2 */
    { {STRENG, 3} }, /* STREAM_ENG_V2 */
  };


  LL_ATON_EnableUnits_Init(Enable_epoch_2_all_units, 8);

}

static void LL_ATON_End_EpochBlock_2(const void *epoch_block)
{
  LL_ATON_LIB_UNUSED(epoch_block);

  static const LL_Switch_DeinitTypeDef switch_deinit_in_2[] = {
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, CONVACC, 0, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 0, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_4 IN: in unit=CONV_ACC_V2 0 in port=0 out unit=STREAM_ENG_V2 0 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, CONVACC, 0, 1), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 3, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_4 IN: in unit=CONV_ACC_V2 0 in port=1 out unit=STREAM_ENG_V2 3 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, ARITH, 1, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, CONVACC, 0, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_4_mul_scale_9 IN: in unit=ARITH_ACC_V2 1 in port=0 out unit=CONV_ACC_V2 0 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, ARITH, 2, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, ARITH, 1, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_4_off_bias_12 IN: in unit=ARITH_ACC_V2 2 in port=0 out unit=ARITH_ACC_V2 1 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, POOL, 0, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, ARITH, 2, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* MaxPool_7 IN: in unit=POOL_ACC_V2 0 in port=0 out unit=ARITH_ACC_V2 2 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, ARITH, 3, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, POOL, 0, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_8_suboff_15 IN: in unit=ARITH_ACC_V2 3 in port=0 out unit=POOL_ACC_V2 0 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, STRENG, 7, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, ARITH, 3, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_8_suboff_15 OUT: in unit=STREAM_ENG_V2 7 in port=0 out unit=ARITH_ACC_V2 3 out port=0 */
  };


  /* epoch=2 */
  LL_Switch_Deinit(switch_deinit_in_2, 7);

  static const LL_ATON_DisableUnits_InitTypeDef Disable_epoch_2_all_units[] = {
    { {STRENG, 7} }, /* STREAM_ENG_V2 */
    { {CONVACC, 0} }, /* CONV_ACC_V2 */
    { {ARITH, 1} }, /* ARITH_ACC_V2 */
    { {ARITH, 2} }, /* ARITH_ACC_V2 */
    { {ARITH, 3} }, /* ARITH_ACC_V2 */
    { {POOL, 0} }, /* POOL_ACC_V2 */
    { {STRENG, 0} }, /* STREAM_ENG_V2 */
    { {STRENG, 3} }, /* STREAM_ENG_V2 */
  };


  LL_ATON_DisableUnits_Init(Disable_epoch_2_all_units, 8);

}


/* scheduling epoch=3    nodes=5   ------------------------------------------------------------------- */

static void LL_ATON_Start_EpochBlock_3(const void *epoch_block)
{
  LL_ATON_LIB_UNUSED(epoch_block);

  /* Unit= 11 [CONV_ACC_V2 1] */
  /* kind=Conv node=Conv2D_8 */
  static const LL_Convacc_InitTypeDef Conv2D_8_init3 = {
    .simd = 1,
    .fsub = 0,
    .accumulate = 0,
    .kfilt_tot = 16,
    .kfilt_first = 0,
    .kfilt_last = 7,
    .rounding_f = 0,
    .saturation_f = 0,
    .round_mode_f = 0,
    .f_unsigned = 1,
    .k_unsigned = 0,
    .deepmode = 0,
    .dss2mode = 0,
    .kseten = 0,
    .zfbias = 0,
    .inbytes_f = 1,
    .shift_f = 0,
    .shift_a = 3,
    .rounding_o = 1,
    .saturation_o = 1,
    .round_mode_o = 1,
    .relu_mode_o = 0,
    .outbytes_o = 3,
    .shift_o = 0,
    .raw_o = 1,
    .fWidth = 4,
    .fHeight = 4,
    .kernelWidth = 3,
    .kernelHeight = 3,
    .nKernels = 8,
    .batchDepth = 8,
    .hstride = 1,
    .vstride = 1,
    .left_padding = 1,
    .right_padding = 1,
    .top_padding = 1,
    .bot_padding = 1,
    .left_crop = 0,
    .right_crop = 3,
    .top_crop = 0,
    .bot_crop = 3,
  };

  /* Unit=CONV_ACC_V2 */
  LL_Convacc_Init(1, &Conv2D_8_init3);


  /* Unit= 12 [CONV_ACC_V2 2] */
  /* kind=Conv node=Conv2D_8_ca_pipe_1 */
  static const LL_Convacc_InitTypeDef Conv2D_8_ca_pipe_1_init3 = {
    .simd = 1,
    .fsub = 0,
    .accumulate = 1,
    .accumulate_first = 1,
    .kfilt_tot = 16,
    .kfilt_first = 8,
    .kfilt_last = 15,
    .rounding_f = 0,
    .saturation_f = 0,
    .round_mode_f = 0,
    .f_unsigned = 1,
    .k_unsigned = 0,
    .deepmode = 0,
    .dss2mode = 0,
    .kseten = 0,
    .zfbias = 0,
    .inbytes_f = 1,
    .shift_f = 0,
    .shift_a = 0,
    .rounding_o = 1,
    .saturation_o = 1,
    .round_mode_o = 1,
    .relu_mode_o = 0,
    .outbytes_o = 2,
    .shift_o = 3,
    .raw_o = 0,
    .fWidth = 4,
    .fHeight = 4,
    .kernelWidth = 3,
    .kernelHeight = 3,
    .nKernels = 8,
    .batchDepth = 8,
    .hstride = 1,
    .vstride = 1,
    .left_padding = 1,
    .right_padding = 1,
    .top_padding = 1,
    .bot_padding = 1,
    .left_crop = 0,
    .right_crop = 3,
    .top_crop = 0,
    .bot_crop = 3,
  };

  /* Unit=CONV_ACC_V2 */
  LL_Convacc_Init(2, &Conv2D_8_ca_pipe_1_init3);


  /* Unit= 18 [ARITH_ACC_V2 0] */
  /* kind=Mul node=Conv2D_8_mul_scale_18 */
  static const LL_Arithacc_InitTypeDef Conv2D_8_mul_scale_18_init3 = {
    .rounding_x = 0,
    .saturation_x = 0,
    .round_mode_x = 0,
    .inbytes_x = 2,
    .outbytes_x = 2,
    .shift_x = 0,
    .rounding_y = 0,
    .saturation_y = 0,
    .round_mode_y = 0,
    .inbytes_y = 2,
    .outbytes_y = 2,
    .combinebc = 0,
    .clipout = 0,
    .shift_y = 0,
    .rounding_o = 1,
    .saturation_o = 1,
    .round_mode_o = 1,
    .relu_mode_o = 0,
    .outbytes_o = 2,
    .shift_o = 14,
    .scalar = 1,
    .dualinput = 0,
    .operation = ARITH_AFFINE,
    .bcast = ARITH_BCAST_SCALAR,
    .Ax_shift = 0,
    .By_shift = 0,
    .C_shift = 0,
    .fWidth = 4,
    .fHeight = 4,
    .fChannels = 32,
    .batchDepth = 8,
    .clipmin = 0,
    .clipmax = 0,
    .A_scalar = 32562,
    .B_scalar = 0,
    .C_scalar = 0,
    .A_vector = {0},
    .B_vector = {0},
    .C_vector = {0},
    .vec_precision = {16, 16, 16},
  };

  /* Unit=ARITH_ACC_V2 */
  LL_Arithacc_Init(0, &Conv2D_8_mul_scale_18_init3);


  /* Unit= 19 [ARITH_ACC_V2 1] */
  /* kind=Add node=Conv2D_8_off_bias_21 */
  static const LL_Arithacc_InitTypeDef Conv2D_8_off_bias_21_init3 = {
    .rounding_x = 0,
    .saturation_x = 0,
    .round_mode_x = 0,
    .inbytes_x = 2,
    .outbytes_x = 2,
    .shift_x = 0,
    .rounding_y = 0,
    .saturation_y = 0,
    .round_mode_y = 0,
    .inbytes_y = 2,
    .outbytes_y = 2,
    .combinebc = 1,
    .clipout = 0,
    .shift_y = 0,
    .rounding_o = 1,
    .saturation_o = 1,
    .round_mode_o = 1,
    .relu_mode_o = 0,
    .outbytes_o = 1,
    .shift_o = 20,
    .scalar = 0,
    .dualinput = 0,
    .operation = ARITH_AFFINE,
    .bcast = ARITH_BCAST_CHAN,
    .Ax_shift = 0,
    .By_shift = 0,
    .C_shift = 0,
    .fWidth = 4,
    .fHeight = 4,
    .fChannels = 32,
    .batchDepth = 8,
    .clipmin = 0,
    .clipmax = 0,
    .A_scalar = 17620,
    .B_scalar = 0,
    .C_scalar = (short)0,
    .A_vector = {0},
    .B_vector = {0},
    .C_vector = {((unsigned char *)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x71000000UL + 5408))) /* Equivalent hex address = 0x71001520UL */},
    .vec_precision = {16, 16, 32},
  };

  /* Unit=ARITH_ACC_V2 */
  LL_Arithacc_Init(1, &Conv2D_8_off_bias_21_init3);


  /* Unit= 23 [POOL_ACC_V2 1] */
  /* kind=MaxPool node=MaxPool_11 */
  static const LL_Poolacc_InitTypeDef MaxPool_11_init3 = {
    .operation = POOL_MAX,
    .avgnopad = 0,
    .inputX = 4,
    .inputY = 4,
    .outputX = 2,
    .outputY = 2,
    .poolWinX = 2,
    .poolWinY = 2,
    .strideX = 2,
    .strideY = 2,
    .topCrop = 0,
    .bottomCrop = 3,
    .leftCrop = 0,
    .rightCrop = 3,
    .topPad = 0,
    .bottomPad = 0,
    .leftPad = 0,
    .rightPad = 0,
    .batchSize = 8,
    .shift_f = 0,
    .shift_o = 0,
    .dualLine = 1,
    .rounding_f = 0,
    .saturation_f = 0,
    .round_mode_f = 0,
    .inbytes_f = 1,
    .outbytes_f = 1,
    .rounding_o = 1,
    .saturation_o = 1,
    .round_mode_o = 1,
    .relu_mode_o = 0,
    .outbytes_o = 1,
    .mulval = 0,
    .pad_val_en = 0,
    .pad_val = 0,
  };

  /* Unit=POOL_ACC_V2 */
  LL_Poolacc_Init(1, &MaxPool_11_init3);


  /* Dma inputs units to cycle: */
  /* Unit= 1 [STREAM_ENG_V2 1] */
  /* Emit conf for STREAM_ENG_V2 node=Conv2D_8 input ports=0 range=1[0,256] */

  static const LL_Streng_TensorInitTypeDef Conv2D_8_dma_init_in_0_3 = {
    /* 4x4x8(8 bits) */
    .dir = 0,
    .raw = 1,
    .noblk = 0,
    .align_right = 0,
    .nbits_unsigned = 1,
    .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */}, /* Conv2D_8_zero_off_out_16 */
    .offset_start = 0,
    .offset_end = 128,
    .offset_limit = 320,
    .frame_count = 0,
    .fwidth = 0,
    .fheight = 0,
    .batch_depth = 0,
    .batch_offset = 0,
    .frame_offset = 256,
    .line_offset = 0,
    .loop_offset = 0,
    .frame_loop_cnt = 1,
    .frame_tot_cnt = 4,
    .nbits_in = 8,
    .nbits_out = 8,
  };

  /* Unit=STREAM_ENG_V2 */
  LL_Streng_TensorInit(1, &Conv2D_8_dma_init_in_0_3, 1);

  /* Unit= 6 [STREAM_ENG_V2 6] */
  /* Emit conf for STREAM_ENG_V2 node=Conv2D_8 input ports=1 range=8[0,4608] */

  static const LL_Streng_TensorInitTypeDef Conv2D_8_dma_init_in_1_3 = {
    /* 32x3x3x16(8 bits) */
    .dir = 0,
    .raw = 1,
    .continuous = 1,
    .noblk = 0,
    .align_right = 0,
    .nbits_unsigned = 0,
    .cacheable = 1,
    .cache_allocate = 0,
    .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */}, /* Conv2D_8_weights */
    .offset_start = 0,
    .offset_end = 576,
    .offset_limit = 4672,
    .frame_count = 0,
    .fwidth = 0,
    .fheight = 0,
    .batch_depth = 0,
    .batch_offset = 0,
    .frame_offset = 576,
    .line_offset = 0,
    .loop_offset = 0,
    .frame_loop_cnt = 0,
    .frame_tot_cnt = 8,
    .nbits_in = 8,
    .nbits_out = 8,
  };

  /* Unit=STREAM_ENG_V2 */
  LL_Streng_TensorInit(6, &Conv2D_8_dma_init_in_1_3, 1);

  /* Unit= 3 [STREAM_ENG_V2 3] */
  /* Emit conf for STREAM_ENG_V2 node=Conv2D_8_ca_pipe_1 input ports=0 range=1[0,256] */

  static const LL_Streng_TensorInitTypeDef Conv2D_8_ca_pipe_1_dma_init_in_0_3 = {
    /* 4x4x8(8 bits) */
    .dir = 0,
    .raw = 1,
    .noblk = 0,
    .align_right = 0,
    .nbits_unsigned = 1,
    .addr_base = {(unsigned char *)ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */}, /* Conv2D_8_zero_off_out_16_copy_in_3 ca pipe offset=1 */
    .offset_start = 128,
    .offset_end = 256,
    .offset_limit = 320,
    .frame_count = 0,
    .fwidth = 0,
    .fheight = 0,
    .batch_depth = 0,
    .batch_offset = 0,
    .frame_offset = 256,
    .line_offset = 0,
    .loop_offset = 0,
    .frame_loop_cnt = 1,
    .frame_tot_cnt = 4,
    .nbits_in = 8,
    .nbits_out = 8,
  };

  /* Unit=STREAM_ENG_V2 */
  LL_Streng_TensorInit(3, &Conv2D_8_ca_pipe_1_dma_init_in_0_3, 1);


  /* Dma input bandwidth from memory pools: */
  /* npuRAM5 -> 256 */
  /* octoFlash -> 4608 */

  /* Dma output units from cycle: */
  /* Unit= 5 [STREAM_ENG_V2 5] */
  /* Emit conf for STREAM_ENG_V2 node=MaxPool_11 output ports=0 range=1[256,384] */

  static const LL_Streng_TensorInitTypeDef MaxPool_11_dma_init_out_0_3 = {
    /* to memory canonical from batch=8 */
    .dir = 1,
    .noblk = 0,
    .align_right = 0,
    .nbits_unsigned = 0,
    .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */}, /* MaxPool_11_out_0 */
    .offset_start = 256,
    .offset_limit = 448,
    .frame_count = 0,
    .fwidth = 2,
    .fheight = 2,
    .batch_depth = 8,
    .batch_offset = 32,
    .frame_offset = 8,
    .line_offset = 0,
    .loop_offset = 128,
    .frame_loop_cnt = 4,
    .frame_tot_cnt = 4,
    .nbits_in = 8,
    .nbits_out = 8,
  };

  /* Unit=STREAM_ENG_V2 */
  LL_Streng_TensorInit(5, &MaxPool_11_dma_init_out_0_3, 1);


  /* Dma output bandwidth to memory pools: */
  /* npuRAM5 <- 128 */

  static const LL_Switch_InitTypeDef switch_init_in_3[] = {
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, CONVACC, 1, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 1, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_8 IN: in unit=CONV_ACC_V2 1 in port=0 out unit=STREAM_ENG_V2 1 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, CONVACC, 1, 1), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 6, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_8 IN: in unit=CONV_ACC_V2 1 in port=1 out unit=STREAM_ENG_V2 6 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, CONVACC, 2, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 3, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_8_ca_pipe_1 IN: in unit=CONV_ACC_V2 2 in port=0 out unit=STREAM_ENG_V2 3 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, CONVACC, 2, 1), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 6, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_8_ca_pipe_1 IN: in unit=CONV_ACC_V2 2 in port=1 out unit=STREAM_ENG_V2 6 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, CONVACC, 2, 2), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, CONVACC, 1, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_8_ca_pipe_1 IN: in unit=CONV_ACC_V2 2 in port=2 out unit=CONV_ACC_V2 1 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, ARITH, 0, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, CONVACC, 2, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_8_mul_scale_18 IN: in unit=ARITH_ACC_V2 0 in port=0 out unit=CONV_ACC_V2 2 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, ARITH, 1, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, ARITH, 0, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_8_off_bias_21 IN: in unit=ARITH_ACC_V2 1 in port=0 out unit=ARITH_ACC_V2 0 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, POOL, 1, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, ARITH, 1, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* MaxPool_11 IN: in unit=POOL_ACC_V2 1 in port=0 out unit=ARITH_ACC_V2 1 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, STRENG, 5, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, POOL, 1, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* MaxPool_11 OUT: in unit=STREAM_ENG_V2 5 in port=0 out unit=POOL_ACC_V2 1 out port=0 */
  };


  /* epoch=3 */
  LL_Switch_Init(switch_init_in_3, 9);

  static const LL_ATON_EnableUnits_InitTypeDef Enable_epoch_3_all_units[] = {
    { {STRENG, 5} }, /* STREAM_ENG_V2 */
    { {CONVACC, 1} }, /* CONV_ACC_V2 */
    { {CONVACC, 2} }, /* CONV_ACC_V2 */
    { {ARITH, 0} }, /* ARITH_ACC_V2 */
    { {ARITH, 1} }, /* ARITH_ACC_V2 */
    { {POOL, 1} }, /* POOL_ACC_V2 */
    { {STRENG, 1} }, /* STREAM_ENG_V2 */
    { {STRENG, 3} }, /* STREAM_ENG_V2 */
    { {STRENG, 6} }, /* STREAM_ENG_V2 */
  };


  LL_ATON_EnableUnits_Init(Enable_epoch_3_all_units, 9);

}

static void LL_ATON_End_EpochBlock_3(const void *epoch_block)
{
  LL_ATON_LIB_UNUSED(epoch_block);

  static const LL_Switch_DeinitTypeDef switch_deinit_in_3[] = {
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, CONVACC, 1, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 1, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_8 IN: in unit=CONV_ACC_V2 1 in port=0 out unit=STREAM_ENG_V2 1 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, CONVACC, 1, 1), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 6, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_8 IN: in unit=CONV_ACC_V2 1 in port=1 out unit=STREAM_ENG_V2 6 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, CONVACC, 2, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 3, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_8_ca_pipe_1 IN: in unit=CONV_ACC_V2 2 in port=0 out unit=STREAM_ENG_V2 3 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, CONVACC, 2, 1), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 6, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_8_ca_pipe_1 IN: in unit=CONV_ACC_V2 2 in port=1 out unit=STREAM_ENG_V2 6 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, CONVACC, 2, 2), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, CONVACC, 1, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_8_ca_pipe_1 IN: in unit=CONV_ACC_V2 2 in port=2 out unit=CONV_ACC_V2 1 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, ARITH, 0, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, CONVACC, 2, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_8_mul_scale_18 IN: in unit=ARITH_ACC_V2 0 in port=0 out unit=CONV_ACC_V2 2 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, ARITH, 1, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, ARITH, 0, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Conv2D_8_off_bias_21 IN: in unit=ARITH_ACC_V2 1 in port=0 out unit=ARITH_ACC_V2 0 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, POOL, 1, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, ARITH, 1, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* MaxPool_11 IN: in unit=POOL_ACC_V2 1 in port=0 out unit=ARITH_ACC_V2 1 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, STRENG, 5, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, POOL, 1, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* MaxPool_11 OUT: in unit=STREAM_ENG_V2 5 in port=0 out unit=POOL_ACC_V2 1 out port=0 */
  };


  /* epoch=3 */
  LL_Switch_Deinit(switch_deinit_in_3, 9);

  static const LL_ATON_DisableUnits_InitTypeDef Disable_epoch_3_all_units[] = {
    { {STRENG, 5} }, /* STREAM_ENG_V2 */
    { {CONVACC, 1} }, /* CONV_ACC_V2 */
    { {CONVACC, 2} }, /* CONV_ACC_V2 */
    { {ARITH, 0} }, /* ARITH_ACC_V2 */
    { {ARITH, 1} }, /* ARITH_ACC_V2 */
    { {POOL, 1} }, /* POOL_ACC_V2 */
    { {STRENG, 1} }, /* STREAM_ENG_V2 */
    { {STRENG, 3} }, /* STREAM_ENG_V2 */
    { {STRENG, 6} }, /* STREAM_ENG_V2 */
  };


  LL_ATON_DisableUnits_Init(Disable_epoch_3_all_units, 9);

}


/* scheduling epoch=4    nodes=1   ------------------------------------------------------------------- */
/* no resources allocated to kind=Reshape node=Gemm_13_reshape_x_2 */

static void LL_ATON_Start_EpochBlock_4(const void *epoch_block)
{
  LL_ATON_LIB_UNUSED(epoch_block);

  /* Unit= 28 [NULL_UNIT 0] */
  /* kind=Reshape node=Gemm_13_reshape_x_2 */
  /* node=Gemm_13_reshape_x_2 satisfies input and output adjacency (DMA->DMA) and can be omitted */

  /* Dma inputs units to cycle: */
  /* Unit= 9 [STREAM_ENG_V2 9] */
  /* Emit conf for STREAM_ENG_V2 node=Gemm_13_reshape_x_2 input ports=0 range=1[256,384] */

  static const LL_Streng_TensorInitTypeDef Gemm_13_reshape_x_2_dma_init_in_0_4 = {
    /* memory canonical to batch=1 */
    .dir = 0,
    .noblk = 0,
    .align_right = 0,
    .nbits_unsigned = 0,
    .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */}, /* Gemm_13_transp_x_0 */
    .offset_start = 256,
    .offset_limit = 448,
    .frame_count = 0,
    .fwidth = 2,
    .fheight = 2,
    .batch_depth = 1,
    .batch_offset = 32,
    .frame_offset = 1,
    .line_offset = 0,
    .loop_offset = 128,
    .frame_loop_cnt = 32,
    .frame_tot_cnt = 32,
    .nbits_in = 8,
    .nbits_out = 8,
  };

  /* Unit=STREAM_ENG_V2 */
  LL_Streng_TensorInit(9, &Gemm_13_reshape_x_2_dma_init_in_0_4, 1);


  /* Dma input bandwidth from memory pools: */
  /* npuRAM5 -> 128 */

  /* Dma output units from cycle: */
  /* Unit= 3 [STREAM_ENG_V2 3] */
  /* Emit conf for STREAM_ENG_V2 node=Gemm_13_reshape_x_2 output ports=0 range=1[0,128] */

  static const LL_Streng_TensorInitTypeDef Gemm_13_reshape_x_2_dma_init_out_0_4 = {
    /* to memory with batch=1 */
    .dir = 1,
    .raw = 1,
    .noblk = 0,
    .align_right = 0,
    .nbits_unsigned = 0,
    .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */}, /* Gemm_13_reshape_x_2 */
    .offset_start = 0,
    .offset_end = 1,
    .offset_limit = 192,
    .frame_count = 0,
    .fwidth = 0,
    .fheight = 0,
    .batch_depth = 0,
    .batch_offset = 0,
    .frame_offset = 1,
    .line_offset = 0,
    .loop_offset = 0,
    .frame_loop_cnt = 0,
    .frame_tot_cnt = 128,
    .nbits_in = 8,
    .nbits_out = 8,
  };

  /* Unit=STREAM_ENG_V2 */
  LL_Streng_TensorInit(3, &Gemm_13_reshape_x_2_dma_init_out_0_4, 1);


  /* Dma output bandwidth to memory pools: */
  /* npuRAM5 <- 128 */

  static const LL_Switch_InitTypeDef switch_init_in_4[] = {
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, STRENG, 3, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 9, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Gemm_13_reshape_x_2 OUT: in unit=STREAM_ENG_V2 3 in port=0 out unit=STREAM_ENG_V2 9 out port=0 */
  };


  /* epoch=4 */
  LL_Switch_Init(switch_init_in_4, 1);

  static const LL_ATON_EnableUnits_InitTypeDef Enable_epoch_4_all_units[] = {
    { {STRENG, 3} }, /* STREAM_ENG_V2 */
    { {STRENG, 9} }, /* STREAM_ENG_V2 */
  };


  LL_ATON_EnableUnits_Init(Enable_epoch_4_all_units, 2);

}

static void LL_ATON_End_EpochBlock_4(const void *epoch_block)
{
  LL_ATON_LIB_UNUSED(epoch_block);

  static const LL_Switch_DeinitTypeDef switch_deinit_in_4[] = {
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, STRENG, 3, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 9, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Gemm_13_reshape_x_2 OUT: in unit=STREAM_ENG_V2 3 in port=0 out unit=STREAM_ENG_V2 9 out port=0 */
  };


  /* epoch=4 */
  LL_Switch_Deinit(switch_deinit_in_4, 1);

  static const LL_ATON_DisableUnits_InitTypeDef Disable_epoch_4_all_units[] = {
    { {STRENG, 3} }, /* STREAM_ENG_V2 */
    { {STRENG, 9} }, /* STREAM_ENG_V2 */
  };


  LL_ATON_DisableUnits_Init(Disable_epoch_4_all_units, 2);

}


/* scheduling epoch=5    nodes=1   ------------------------------------------------------------------- */

static void LL_ATON_Start_EpochBlock_5(const void *epoch_block)
{
  LL_ATON_LIB_UNUSED(epoch_block);

  /* Unit= 20 [ARITH_ACC_V2 2] */
  /* kind=Sub node=Gemm_13_conv_4_suboff_24 */
  static const LL_Arithacc_InitTypeDef Gemm_13_conv_4_suboff_24_init5 = {
    .rounding_x = 0,
    .saturation_x = 0,
    .round_mode_x = 0,
    .inbytes_x = 1,
    .outbytes_x = 1,
    .shift_x = 0,
    .rounding_y = 0,
    .saturation_y = 0,
    .round_mode_y = 0,
    .inbytes_y = 1,
    .outbytes_y = 1,
    .combinebc = 1,
    .clipout = 0,
    .shift_y = 0,
    .rounding_o = 0,
    .saturation_o = 0,
    .round_mode_o = 1,
    .relu_mode_o = 0,
    .outbytes_o = 1,
    .shift_o = 14,
    .scalar = 1,
    .dualinput = 0,
    .operation = ARITH_AFFINE,
    .bcast = ARITH_BCAST_HEIGHT,
    .Ax_shift = 0,
    .By_shift = 0,
    .C_shift = 0,
    .fWidth = 1,
    .fHeight = 1,
    .fChannels = 128,
    .batchDepth = 1,
    .clipmin = 0,
    .clipmax = 0,
    .A_scalar = 16384,
    .B_scalar = 32,
    .C_scalar = (short)0,
    .A_vector = {0},
    .B_vector = {0},
    .C_vector = {0},
    .vec_precision = {8, 8, 8},
  };

  /* Unit=ARITH_ACC_V2 */
  LL_Arithacc_Init(2, &Gemm_13_conv_4_suboff_24_init5);


  /* Dma inputs units to cycle: */
  /* Unit= 9 [STREAM_ENG_V2 9] */
  /* Emit conf for STREAM_ENG_V2 node=Gemm_13_conv_4_suboff_24 input ports=0 range=1[0,128] */

  static const LL_Streng_TensorInitTypeDef Gemm_13_conv_4_suboff_24_dma_init_in_0_5 = {
    /* from memory with batch=1 */
    .dir = 0,
    .raw = 1,
    .noblk = 0,
    .align_right = 0,
    .nbits_unsigned = 0,
    .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */}, /* Gemm_13_reshape_x_2 */
    .offset_start = 0,
    .offset_end = 1,
    .offset_limit = 192,
    .frame_count = 0,
    .fwidth = 0,
    .fheight = 0,
    .batch_depth = 0,
    .batch_offset = 0,
    .frame_offset = 1,
    .line_offset = 0,
    .loop_offset = 0,
    .frame_loop_cnt = 0,
    .frame_tot_cnt = 128,
    .nbits_in = 8,
    .nbits_out = 8,
  };

  /* Unit=STREAM_ENG_V2 */
  LL_Streng_TensorInit(9, &Gemm_13_conv_4_suboff_24_dma_init_in_0_5, 1);


  /* Dma input bandwidth from memory pools: */
  /* npuRAM5 -> 128 */

  /* Dma output units from cycle: */
  /* Unit= 1 [STREAM_ENG_V2 1] */
  /* Emit conf for STREAM_ENG_V2 node=Gemm_13_conv_4_suboff_24 output ports=0 range=1[128,256] */

  static const LL_Streng_TensorInitTypeDef Gemm_13_conv_4_suboff_24_dma_init_out_0_5 = {
    /* to memory with batch=1 */
    .dir = 1,
    .raw = 1,
    .noblk = 0,
    .align_right = 0,
    .nbits_unsigned = 1,
    .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */}, /* Gemm_13_conv_4_zero_off_out_25 */
    .offset_start = 128,
    .offset_end = 129,
    .offset_limit = 320,
    .frame_count = 0,
    .fwidth = 0,
    .fheight = 0,
    .batch_depth = 0,
    .batch_offset = 0,
    .frame_offset = 1,
    .line_offset = 0,
    .loop_offset = 0,
    .frame_loop_cnt = 0,
    .frame_tot_cnt = 128,
    .nbits_in = 8,
    .nbits_out = 8,
  };

  /* Unit=STREAM_ENG_V2 */
  LL_Streng_TensorInit(1, &Gemm_13_conv_4_suboff_24_dma_init_out_0_5, 1);


  /* Dma output bandwidth to memory pools: */
  /* npuRAM5 <- 128 */

  static const LL_Switch_InitTypeDef switch_init_in_5[] = {
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, ARITH, 2, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 9, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Gemm_13_conv_4_suboff_24 IN: in unit=ARITH_ACC_V2 2 in port=0 out unit=STREAM_ENG_V2 9 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, STRENG, 1, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, ARITH, 2, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Gemm_13_conv_4_suboff_24 OUT: in unit=STREAM_ENG_V2 1 in port=0 out unit=ARITH_ACC_V2 2 out port=0 */
  };


  /* epoch=5 */
  LL_Switch_Init(switch_init_in_5, 2);

  static const LL_ATON_EnableUnits_InitTypeDef Enable_epoch_5_all_units[] = {
    { {STRENG, 1} }, /* STREAM_ENG_V2 */
    { {ARITH, 2} }, /* ARITH_ACC_V2 */
    { {STRENG, 9} }, /* STREAM_ENG_V2 */
  };


  LL_ATON_EnableUnits_Init(Enable_epoch_5_all_units, 3);

}

static void LL_ATON_End_EpochBlock_5(const void *epoch_block)
{
  LL_ATON_LIB_UNUSED(epoch_block);

  static const LL_Switch_DeinitTypeDef switch_deinit_in_5[] = {
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, ARITH, 2, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 9, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Gemm_13_conv_4_suboff_24 IN: in unit=ARITH_ACC_V2 2 in port=0 out unit=STREAM_ENG_V2 9 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, STRENG, 1, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, ARITH, 2, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Gemm_13_conv_4_suboff_24 OUT: in unit=STREAM_ENG_V2 1 in port=0 out unit=ARITH_ACC_V2 2 out port=0 */
  };


  /* epoch=5 */
  LL_Switch_Deinit(switch_deinit_in_5, 2);

  static const LL_ATON_DisableUnits_InitTypeDef Disable_epoch_5_all_units[] = {
    { {STRENG, 1} }, /* STREAM_ENG_V2 */
    { {ARITH, 2} }, /* ARITH_ACC_V2 */
    { {STRENG, 9} }, /* STREAM_ENG_V2 */
  };


  LL_ATON_DisableUnits_Init(Disable_epoch_5_all_units, 3);

}


/* scheduling epoch=6    nodes=4   ------------------------------------------------------------------- */

static void LL_ATON_Start_EpochBlock_6(const void *epoch_block)
{
  LL_ATON_LIB_UNUSED(epoch_block);

  /* Unit= 13 [CONV_ACC_V2 3] */
  /* kind=Conv node=Gemm_13_conv_4 */
  static const LL_Convacc_InitTypeDef Gemm_13_conv_4_init6 = {
    .simd = 1,
    .fsub = 0,
    .accumulate = 0,
    .rounding_f = 0,
    .saturation_f = 0,
    .round_mode_f = 0,
    .f_unsigned = 1,
    .k_unsigned = 0,
    .deepmode = 1,
    .dss2mode = 0,
    .kseten = 3,
    .zfbias = 0,
    .inbytes_f = 3,
    .shift_f = 0,
    .shift_a = 4,
    .rounding_o = 1,
    .saturation_o = 1,
    .round_mode_o = 1,
    .relu_mode_o = 0,
    .outbytes_o = 2,
    .shift_o = 4,
    .raw_o = 0,
    .fWidth = 1,
    .fHeight = 1,
    .kernelWidth = 1,
    .kernelHeight = 1,
    .nKernels = 5,
    .batchDepth = 128,
    .hstride = 1,
    .vstride = 1,
    .left_padding = 0,
    .right_padding = 0,
    .top_padding = 0,
    .bot_padding = 0,
    .left_crop = 0,
    .right_crop = 0,
    .top_crop = 0,
    .bot_crop = 0,
  };

  /* Unit=CONV_ACC_V2 */
  LL_Convacc_Init(3, &Gemm_13_conv_4_init6);


  /* Unit= 21 [ARITH_ACC_V2 3] */
  /* kind=Mul node=Gemm_13_conv_4_mul_scale_27 */
  static const LL_Arithacc_InitTypeDef Gemm_13_conv_4_mul_scale_27_init6 = {
    .rounding_x = 0,
    .saturation_x = 0,
    .round_mode_x = 0,
    .inbytes_x = 2,
    .outbytes_x = 2,
    .shift_x = 0,
    .rounding_y = 0,
    .saturation_y = 0,
    .round_mode_y = 0,
    .inbytes_y = 2,
    .outbytes_y = 2,
    .combinebc = 0,
    .clipout = 0,
    .shift_y = 0,
    .rounding_o = 1,
    .saturation_o = 1,
    .round_mode_o = 1,
    .relu_mode_o = 0,
    .outbytes_o = 2,
    .shift_o = 15,
    .scalar = 1,
    .dualinput = 0,
    .operation = ARITH_AFFINE,
    .bcast = ARITH_BCAST_HEIGHT,
    .Ax_shift = 0,
    .By_shift = 0,
    .C_shift = 0,
    .fWidth = 1,
    .fHeight = 1,
    .fChannels = 5,
    .batchDepth = 5,
    .clipmin = 0,
    .clipmax = 0,
    .A_scalar = 23698,
    .B_scalar = 0,
    .C_scalar = 0,
    .A_vector = {0},
    .B_vector = {0},
    .C_vector = {0},
    .vec_precision = {16, 16, 16},
  };

  /* Unit=ARITH_ACC_V2 */
  LL_Arithacc_Init(3, &Gemm_13_conv_4_mul_scale_27_init6);


  /* Unit= 18 [ARITH_ACC_V2 0] */
  /* kind=Add node=Gemm_13_conv_4_off_bias_30 */
  static const LL_Arithacc_InitTypeDef Gemm_13_conv_4_off_bias_30_init6 = {
    .rounding_x = 0,
    .saturation_x = 0,
    .round_mode_x = 0,
    .inbytes_x = 2,
    .outbytes_x = 2,
    .shift_x = 0,
    .rounding_y = 0,
    .saturation_y = 0,
    .round_mode_y = 0,
    .inbytes_y = 2,
    .outbytes_y = 2,
    .combinebc = 1,
    .clipout = 0,
    .shift_y = 0,
    .rounding_o = 1,
    .saturation_o = 1,
    .round_mode_o = 1,
    .relu_mode_o = 0,
    .outbytes_o = 1,
    .shift_o = 20,
    .scalar = 0,
    .dualinput = 0,
    .operation = ARITH_AFFINE,
    .bcast = ARITH_BCAST_CHAN,
    .Ax_shift = 0,
    .By_shift = 0,
    .C_shift = 0,
    .fWidth = 1,
    .fHeight = 1,
    .fChannels = 5,
    .batchDepth = 5,
    .clipmin = 0,
    .clipmax = 0,
    .A_scalar = 21042,
    .B_scalar = 0,
    .C_scalar = (short)0,
    .A_vector = {0},
    .B_vector = {0},
    .C_vector = {((unsigned char *)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x71000000UL + 5600))) /* Equivalent hex address = 0x710015e0UL */},
    .vec_precision = {16, 16, 32},
  };

  /* Unit=ARITH_ACC_V2 */
  LL_Arithacc_Init(0, &Gemm_13_conv_4_off_bias_30_init6);


  /* Dma inputs units to cycle: */
  /* Unit= 1 [STREAM_ENG_V2 1] */
  /* Emit conf for STREAM_ENG_V2 node=Gemm_13_conv_4 input ports=0 range=1[128,256] */

  static const LL_Streng_TensorInitTypeDef Gemm_13_conv_4_dma_init_in_0_6 = {
    /* 1x1x128(8 bits) */
    .dir = 0,
    .raw = 1,
    .raw_out = 1,
    .noblk = 0,
    .align_right = 0,
    .nbits_unsigned = 1,
    .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */}, /* Gemm_13_conv_4_zero_off_out_25 */
    .offset_start = 128,
    .offset_end = 257,
    .offset_limit = 320,
    .frame_count = 0,
    .fwidth = 0,
    .fheight = 0,
    .batch_depth = 0,
    .batch_offset = 0,
    .frame_offset = 0,
    .line_offset = 0,
    .loop_offset = 128,
    .frame_loop_cnt = 1,
    .frame_tot_cnt = 1,
    .nbits_in = 24,
    .nbits_out = 24,
  };

  /* Unit=STREAM_ENG_V2 */
  LL_Streng_TensorInit(1, &Gemm_13_conv_4_dma_init_in_0_6, 1);

  /* Unit= 7 [STREAM_ENG_V2 7] */
  /* Emit conf for STREAM_ENG_V2 node=Gemm_13_conv_4 input ports=1 range=8[4608,5250] */

  static const LL_Streng_TensorInitTypeDef Gemm_13_conv_4_dma_init_in_1_6 = {
    /* 5x1x1x128(8 bits) */
    .dir = 0,
    .raw = 1,
    .continuous = 1,
    .noblk = 0,
    .align_right = 0,
    .nbits_unsigned = 0,
    .cacheable = 1,
    .cache_allocate = 0,
    .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */}, /* Gemm_13_weights_transposed_3 */
    .offset_start = 4608,
    .offset_end = 5250,
    .offset_limit = 5320,
    .frame_count = 0,
    .fwidth = 0,
    .fheight = 0,
    .batch_depth = 0,
    .batch_offset = 0,
    .frame_offset = 0,
    .line_offset = 0,
    .loop_offset = 0,
    .frame_loop_cnt = 0,
    .frame_tot_cnt = 1,
    .nbits_in = 24,
    .nbits_out = 24,
  };

  /* Unit=STREAM_ENG_V2 */
  LL_Streng_TensorInit(7, &Gemm_13_conv_4_dma_init_in_1_6, 1);


  /* Dma input bandwidth from memory pools: */
  /* npuRAM5 -> 128 */
  /* octoFlash -> 640 */

  /* Dma output units from cycle: */
  /* Unit= 6 [STREAM_ENG_V2 6] */
  /* Emit conf for STREAM_ENG_V2 node=Gemm_13_conv_4_off_bias_30 output ports=0 range=1[0,5] */

  static const LL_Streng_TensorInitTypeDef Gemm_13_conv_4_off_bias_30_dma_init_out_0_6 = {
    /* to memory with batch=5 */
    .dir = 1,
    .raw = 1,
    .noblk = 0,
    .align_right = 0,
    .nbits_unsigned = 0,
    .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */}, /* Gemm_13_conv_4_off_bias_out_31 */
    .offset_start = 0,
    .offset_end = 5,
    .offset_limit = 72,
    .frame_count = 0,
    .fwidth = 0,
    .fheight = 0,
    .batch_depth = 0,
    .batch_offset = 0,
    .frame_offset = 5,
    .line_offset = 0,
    .loop_offset = 0,
    .frame_loop_cnt = 0,
    .frame_tot_cnt = 1,
    .nbits_in = 8,
    .nbits_out = 8,
  };

  /* Unit=STREAM_ENG_V2 */
  LL_Streng_TensorInit(6, &Gemm_13_conv_4_off_bias_30_dma_init_out_0_6, 1);


  /* Dma output bandwidth to memory pools: */
  /* npuRAM5 <- 5 */

  static const LL_Switch_InitTypeDef switch_init_in_6[] = {
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, CONVACC, 3, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 1, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Gemm_13_conv_4 IN: in unit=CONV_ACC_V2 3 in port=0 out unit=STREAM_ENG_V2 1 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, CONVACC, 3, 1), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 7, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Gemm_13_conv_4 IN: in unit=CONV_ACC_V2 3 in port=1 out unit=STREAM_ENG_V2 7 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, ARITH, 3, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, CONVACC, 3, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Gemm_13_conv_4_mul_scale_27 IN: in unit=ARITH_ACC_V2 3 in port=0 out unit=CONV_ACC_V2 3 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, ARITH, 0, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, ARITH, 3, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Gemm_13_conv_4_off_bias_30 IN: in unit=ARITH_ACC_V2 0 in port=0 out unit=ARITH_ACC_V2 3 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, STRENG, 6, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, ARITH, 0, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Gemm_13_conv_4_off_bias_30 OUT: in unit=STREAM_ENG_V2 6 in port=0 out unit=ARITH_ACC_V2 0 out port=0 */
  };


  /* epoch=6 */
  LL_Switch_Init(switch_init_in_6, 5);

  /* *** MCU cache invalidate (only) operation (HW, whole range) *** */
  /*     memory pool: 1 */
  /*     start: ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 0))) */
  /*     end:   ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 32))) */
  LL_ATON_Cache_MCU_Invalidate_Range(((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 0))) /* Equivalent hex address = 0x342e0000UL */, 32);

  static const LL_ATON_EnableUnits_InitTypeDef Enable_epoch_6_all_units[] = {
    { {STRENG, 6} }, /* STREAM_ENG_V2 */
    { {CONVACC, 3} }, /* CONV_ACC_V2 */
    { {ARITH, 0} }, /* ARITH_ACC_V2 */
    { {ARITH, 3} }, /* ARITH_ACC_V2 */
    { {STRENG, 1} }, /* STREAM_ENG_V2 */
    { {STRENG, 7} }, /* STREAM_ENG_V2 */
  };


  LL_ATON_EnableUnits_Init(Enable_epoch_6_all_units, 6);

}

static void LL_ATON_End_EpochBlock_6(const void *epoch_block)
{
  LL_ATON_LIB_UNUSED(epoch_block);

  static const LL_Switch_DeinitTypeDef switch_deinit_in_6[] = {
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, CONVACC, 3, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 1, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Gemm_13_conv_4 IN: in unit=CONV_ACC_V2 3 in port=0 out unit=STREAM_ENG_V2 1 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, CONVACC, 3, 1), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, STRENG, 7, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Gemm_13_conv_4 IN: in unit=CONV_ACC_V2 3 in port=1 out unit=STREAM_ENG_V2 7 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, ARITH, 3, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, CONVACC, 3, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Gemm_13_conv_4_mul_scale_27 IN: in unit=ARITH_ACC_V2 3 in port=0 out unit=CONV_ACC_V2 3 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, ARITH, 0, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, ARITH, 3, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Gemm_13_conv_4_off_bias_30 IN: in unit=ARITH_ACC_V2 0 in port=0 out unit=ARITH_ACC_V2 3 out port=0 */
    { LL_Switch_Init_Dest() = ATONN_DSTPORT(STRSWITCH, 0, STRENG, 6, 0), LL_Switch_Init_Source(0) = ATONN_SRCPORT(STRSWITCH, 0, ARITH, 0, 0), LL_Switch_Init_Context(0) = 1, LL_Switch_Init_Frames(0) = 0, }, /* Gemm_13_conv_4_off_bias_30 OUT: in unit=STREAM_ENG_V2 6 in port=0 out unit=ARITH_ACC_V2 0 out port=0 */
  };


  /* epoch=6 */
  LL_Switch_Deinit(switch_deinit_in_6, 5);

  static const LL_ATON_DisableUnits_InitTypeDef Disable_epoch_6_all_units[] = {
    { {STRENG, 6} }, /* STREAM_ENG_V2 */
    { {CONVACC, 3} }, /* CONV_ACC_V2 */
    { {ARITH, 0} }, /* ARITH_ACC_V2 */
    { {ARITH, 3} }, /* ARITH_ACC_V2 */
    { {STRENG, 1} }, /* STREAM_ENG_V2 */
    { {STRENG, 7} }, /* STREAM_ENG_V2 */
  };


  LL_ATON_DisableUnits_Init(Disable_epoch_6_all_units, 6);

}


/* scheduling epoch=7    nodes=1   ------------------------------------------------------------------- */

/* scheduling DONE                 ------------------------------------------------------------------- */

const EpochBlock_ItemTypeDef *LL_ATON_EpochBlockItems_tof_module_v3(void) {

  static const EpochBlock_ItemTypeDef ll_atonn_rt_epoch_block_array[] = {
    {
      .start_epoch_block = LL_ATON_Start_EpochBlock_1,
      .end_epoch_block = LL_ATON_End_EpochBlock_1,
      .wait_mask = 0x00000010,
      .flags = EpochBlock_Flags_epoch_start | EpochBlock_Flags_epoch_end | EpochBlock_Flags_pure_hw,
#ifdef LL_ATON_EB_DBG_INFO
      .epoch_num = 1,
      .last_epoch_num = 1,
      .in_streng_mask = 0x00000200,
      .out_streng_mask = 0x00000010,
      .estimated_npu_cycles = 0,
      .estimated_tot_cycles = 0,
#endif // LL_ATON_EB_DBG_INFO
    },
    {
      .start_epoch_block = LL_ATON_Start_EpochBlock_2,
      .end_epoch_block = LL_ATON_End_EpochBlock_2,
      .wait_mask = 0x00000080,
      .flags = EpochBlock_Flags_epoch_start | EpochBlock_Flags_epoch_end | EpochBlock_Flags_pure_hw,
#ifdef LL_ATON_EB_DBG_INFO
      .epoch_num = 2,
      .last_epoch_num = 2,
      .in_streng_mask = 0x00000009,
      .out_streng_mask = 0x00000080,
      .estimated_npu_cycles = 0,
      .estimated_tot_cycles = 0,
#endif // LL_ATON_EB_DBG_INFO
    },
    {
      .start_epoch_block = LL_ATON_Start_EpochBlock_3,
      .end_epoch_block = LL_ATON_End_EpochBlock_3,
      .wait_mask = 0x00000020,
      .flags = EpochBlock_Flags_epoch_start | EpochBlock_Flags_epoch_end | EpochBlock_Flags_pure_hw,
#ifdef LL_ATON_EB_DBG_INFO
      .epoch_num = 3,
      .last_epoch_num = 3,
      .in_streng_mask = 0x0000004a,
      .out_streng_mask = 0x00000020,
      .estimated_npu_cycles = 0,
      .estimated_tot_cycles = 0,
#endif // LL_ATON_EB_DBG_INFO
    },
    {
      .start_epoch_block = LL_ATON_Start_EpochBlock_4,
      .end_epoch_block = LL_ATON_End_EpochBlock_4,
      .wait_mask = 0x00000008,
      .flags = EpochBlock_Flags_epoch_start | EpochBlock_Flags_epoch_end | EpochBlock_Flags_pure_hw,
#ifdef LL_ATON_EB_DBG_INFO
      .epoch_num = 4,
      .last_epoch_num = 4,
      .in_streng_mask = 0x00000200,
      .out_streng_mask = 0x00000008,
      .estimated_npu_cycles = 0,
      .estimated_tot_cycles = 0,
#endif // LL_ATON_EB_DBG_INFO
    },
    {
      .start_epoch_block = LL_ATON_Start_EpochBlock_5,
      .end_epoch_block = LL_ATON_End_EpochBlock_5,
      .wait_mask = 0x00000002,
      .flags = EpochBlock_Flags_epoch_start | EpochBlock_Flags_epoch_end | EpochBlock_Flags_pure_hw,
#ifdef LL_ATON_EB_DBG_INFO
      .epoch_num = 5,
      .last_epoch_num = 5,
      .in_streng_mask = 0x00000200,
      .out_streng_mask = 0x00000002,
      .estimated_npu_cycles = 0,
      .estimated_tot_cycles = 0,
#endif // LL_ATON_EB_DBG_INFO
    },
    {
      .start_epoch_block = LL_ATON_Start_EpochBlock_6,
      .end_epoch_block = LL_ATON_End_EpochBlock_6,
      .wait_mask = 0x00000040,
      .flags = EpochBlock_Flags_epoch_start | EpochBlock_Flags_epoch_end | EpochBlock_Flags_pure_hw,
#ifdef LL_ATON_EB_DBG_INFO
      .epoch_num = 6,
      .last_epoch_num = 6,
      .in_streng_mask = 0x00000082,
      .out_streng_mask = 0x00000040,
      .estimated_npu_cycles = 0,
      .estimated_tot_cycles = 0,
#endif // LL_ATON_EB_DBG_INFO
    },
    {
      .flags = EpochBlock_Flags_last_eb,
    },
  };


  return ll_atonn_rt_epoch_block_array;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Input_Buffers_Info_tof_module_v3(void)
{
  static const uint32_t buff_info__shape_1_1_8_8[] = { 1, 8, 8, 1 };
  static const uint32_t buff_info__mem_shape_F_1_1_8_8[] = { 1, 1, 8, 8 };
  static const float buff_info_Input_0_out_0_quant_scale[] = { 0.00391558557748795 };
  static const int16_t buff_info_Input_0_out_0_quant_offset[] = { -128 };
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
  static const uint32_t buff_info__shape_16_1_3_3[] = { 16, 3, 3, 1 };
  static const uint32_t buff_info__mem_shape_F_16_1_3_3[] = { 16, 1, 3, 3 };
  static const float buff_info_Conv2D_4_weights_quant_scale[] = { 0.0146015528589487 };
  static const int16_t buff_info_Conv2D_4_weights_quant_offset[] = { 0 };
  static const uint32_t buff_info__shape_32_16_3_3[] = { 32, 3, 3, 16 };
  static const uint32_t buff_info__mem_shape_M_32_16_3_3[] = { 32, 2, 3, 3, 8 };
  static const float buff_info_Conv2D_8_weights_quant_scale[] = { 0.00513999350368977 };
  static const int16_t buff_info_Conv2D_8_weights_quant_offset[] = { 0 };
  static const uint32_t buff_info__shape_5_128_1_1[] = { 5, 1, 1, 128 };
  static const uint32_t buff_info__mem_shape_F_5_128_1_1[] = { 5, 128, 1, 1 };
  static const float buff_info_Gemm_13_weights_transposed_3_quant_scale[] = { 0.00151903217192739 };
  static const int16_t buff_info_Gemm_13_weights_transposed_3_quant_offset[] = { 0 };
  static const uint32_t buff_info__shape_1[] = { 1, 1, 1, 1 };
  static const uint32_t buff_info__mem_shape_U_1[] = { 1 };
  static const float buff_info_Conv2D_4_zero_off_8_quant_scale[] = { 0.00391558557748795 };
  static const int16_t buff_info_Conv2D_4_zero_off_8_quant_offset[] = { 0 };
  static const uint32_t buff_info__shape_16_1_1[] = { 1, 1, 1, 16 };
  static const uint32_t buff_info__mem_shape_M_16_1_1[] = { 2, 1, 1, 8 };
  static const float buff_info_Conv2D_8_zero_off_17_quant_scale[] = { 0.0117999687790871 };
  static const int16_t buff_info_Conv2D_8_zero_off_17_quant_offset[] = { 0 };
  static const uint32_t buff_info__shape_32_1_1[] = { 1, 1, 1, 32 };
  static const uint32_t buff_info__mem_shape_M_32_1_1[] = { 4, 1, 1, 8 };
  static const float buff_info_Gemm_13_conv_4_zero_off_26_quant_scale[] = { 0.0145292747765779 };
  static const int16_t buff_info_Gemm_13_conv_4_zero_off_26_quant_offset[] = { 0 };
  static const uint32_t buff_info__shape_5_1_1[] = { 1, 1, 1, 5 };
  static const uint32_t buff_info__mem_shape_F_5_1_1[] = { 5, 1, 1 };
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
  static const LL_Buffer_InfoTypeDef buff_info[] = {
    {
      .name = "Input_0_out_0",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 0,
      .offset_end = 64,
      .offset_limit = 128,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_F_1_1_8_8,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_1_8_8,
      .per_channel = 0,
      .scale = buff_info_Input_0_out_0_quant_scale,
      .offset = buff_info_Input_0_out_0_quant_offset,
    },
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
    {
      .name = "Conv2D_4_weights",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 5264,
      .offset_end = 5408,
      .offset_limit = 5472,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_F_16_1_3_3,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_16_1_3_3,
      .per_channel = 0,
      .scale = buff_info_Conv2D_4_weights_quant_scale,
      .offset = buff_info_Conv2D_4_weights_quant_offset,
    },
    {
      .name = "Conv2D_8_weights",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 0,
      .offset_end = 4608,
      .offset_limit = 4672,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 8,
      .mem_shape = buff_info__mem_shape_M_32_16_3_3,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_32_16_3_3,
      .per_channel = 0,
      .scale = buff_info_Conv2D_8_weights_quant_scale,
      .offset = buff_info_Conv2D_8_weights_quant_offset,
    },
    {
      .name = "Gemm_13_weights_transposed_3",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 4608,
      .offset_end = 5250,
      .offset_limit = 5320,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 128,
      .mem_shape = buff_info__mem_shape_F_5_128_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_5_128_1_1,
      .per_channel = 0,
      .scale = buff_info_Gemm_13_weights_transposed_3_quant_scale,
      .offset = buff_info_Gemm_13_weights_transposed_3_quant_offset,
    },
    {
      .name = "Conv2D_4_zero_off_8",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 5712,
      .offset_end = 5713,
      .offset_limit = 5784,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1,
      .mem_ndims = 1,
      .chpos = CHPos_UNDEFINED,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1,
      .per_channel = 0,
      .scale = buff_info_Conv2D_4_zero_off_8_quant_scale,
      .offset = buff_info_Conv2D_4_zero_off_8_quant_offset,
    },
    {
      .name = "Conv2D_4_mul_scale_11",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 5632,
      .offset_end = 5634,
      .offset_limit = 5704,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1,
      .mem_ndims = 1,
      .chpos = CHPos_UNDEFINED,
      .Qm = -14,
      .Qn = 29,
      .Qunsigned = 0,
      .type = DataType_FXP,
      .nbits = 16,
      .ndims = 4,
      .shape = buff_info__shape_1,
    },
    {
      .name = "Conv2D_4_off_bias_14",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 5536,
      .offset_end = 5600,
      .offset_limit = 5664,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 8,
      .mem_shape = buff_info__mem_shape_M_16_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_Mixed,
      .Qm = 11,
      .Qn = 20,
      .Qunsigned = 0,
      .type = DataType_FXP,
      .nbits = 32,
      .ndims = 4,
      .shape = buff_info__shape_16_1_1,
    },
    {
      .name = "Conv2D_8_zero_off_17",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 5680,
      .offset_end = 5681,
      .offset_limit = 5752,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1,
      .mem_ndims = 1,
      .chpos = CHPos_UNDEFINED,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1,
      .per_channel = 0,
      .scale = buff_info_Conv2D_8_zero_off_17_quant_scale,
      .offset = buff_info_Conv2D_8_zero_off_17_quant_offset,
    },
    {
      .name = "Conv2D_8_mul_scale_20",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 5648,
      .offset_end = 5650,
      .offset_limit = 5720,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1,
      .mem_ndims = 1,
      .chpos = CHPos_UNDEFINED,
      .Qm = -14,
      .Qn = 29,
      .Qunsigned = 0,
      .type = DataType_FXP,
      .nbits = 16,
      .ndims = 4,
      .shape = buff_info__shape_1,
    },
    {
      .name = "Conv2D_8_off_bias_23",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 5408,
      .offset_end = 5536,
      .offset_limit = 5600,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 8,
      .mem_shape = buff_info__mem_shape_M_32_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_Mixed,
      .Qm = 11,
      .Qn = 20,
      .Qunsigned = 0,
      .type = DataType_FXP,
      .nbits = 32,
      .ndims = 4,
      .shape = buff_info__shape_32_1_1,
    },
    {
      .name = "Gemm_13_conv_4_zero_off_26",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 5696,
      .offset_end = 5697,
      .offset_limit = 5768,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1,
      .mem_ndims = 1,
      .chpos = CHPos_UNDEFINED,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1,
      .per_channel = 0,
      .scale = buff_info_Gemm_13_conv_4_zero_off_26_quant_scale,
      .offset = buff_info_Gemm_13_conv_4_zero_off_26_quant_offset,
    },
    {
      .name = "Gemm_13_conv_4_mul_scale_29",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 5664,
      .offset_end = 5666,
      .offset_limit = 5736,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1,
      .mem_ndims = 1,
      .chpos = CHPos_UNDEFINED,
      .Qm = -15,
      .Qn = 30,
      .Qunsigned = 0,
      .type = DataType_FXP,
      .nbits = 16,
      .ndims = 4,
      .shape = buff_info__shape_1,
    },
    {
      .name = "Gemm_13_conv_4_off_bias_32",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 5600,
      .offset_end = 5620,
      .offset_limit = 5688,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 5,
      .mem_shape = buff_info__mem_shape_F_5_1_1,
      .mem_ndims = 3,
      .chpos = CHPos_First,
      .Qm = 11,
      .Qn = 20,
      .Qunsigned = 0,
      .type = DataType_FXP,
      .nbits = 32,
      .ndims = 4,
      .shape = buff_info__shape_5_1_1,
    },
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
    {
      .name = NULL,
    }
  };

  return buff_info;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Output_Buffers_Info_tof_module_v3(void)
{
  static const uint32_t buff_info__shape_1_5[] = { 1, 1, 5, 1 };
  static const uint32_t buff_info__mem_shape_U_1_5[] = { 1, 5 };
  static const float buff_info_Quantize_14_out_0_quant_scale[] = { 0.0243322141468525 };
  static const int16_t buff_info_Quantize_14_out_0_quant_offset[] = { 33 };
  static const LL_Buffer_InfoTypeDef buff_info[] = {
    {
      .name = "Quantize_14_out_0",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 0,
      .offset_end = 5,
      .offset_limit = 72,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 6,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1_5,
      .mem_ndims = 2,
      .chpos = CHPos_UNDEFINED,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_5,
      .per_channel = 0,
      .scale = buff_info_Quantize_14_out_0_quant_scale,
      .offset = buff_info_Quantize_14_out_0_quant_offset,
    },
    {
      .name = NULL,
    }
  };

  return buff_info;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Internal_Buffers_Info_tof_module_v3(void)
{
  static const uint32_t buff_info__shape_1_1_8_8[] = { 1, 8, 8, 1 };
  static const uint32_t buff_info__mem_shape_F_1_1_8_8[] = { 1, 1, 8, 8 };
  static const float buff_info_Conv2D_4_zero_off_out_7_quant_scale[] = { 0.00391558557748795 };
  static const int16_t buff_info_Conv2D_4_zero_off_out_7_quant_offset[] = { 0 };
  static const uint32_t buff_info__shape_1_16_4_4[] = { 1, 4, 4, 16 };
  static const uint32_t buff_info__mem_shape_M_1_16_4_4[] = { 1, 2, 4, 4, 8 };
  static const float buff_info_Conv2D_8_zero_off_out_16_quant_scale[] = { 0.0117999687790871 };
  static const int16_t buff_info_Conv2D_8_zero_off_out_16_quant_offset[] = { 0 };
  static const uint32_t buff_info__shape_1_32_2_2[] = { 1, 2, 2, 32 };
  static const uint32_t buff_info__mem_shape_L_1_32_2_2[] = { 1, 2, 2, 32 };
  static const float buff_info_MaxPool_11_out_0_quant_scale[] = { 0.0145292747765779 };
  static const int16_t buff_info_MaxPool_11_out_0_quant_offset[] = { -128 };
  static const uint32_t buff_info__shape_1_128_1_1[] = { 1, 1, 1, 128 };
  static const uint32_t buff_info__mem_shape_F_1_128_1_1[] = { 1, 128, 1, 1 };
  static const float buff_info_Gemm_13_reshape_x_2_quant_scale[] = { 0.0145292747765779 };
  static const int16_t buff_info_Gemm_13_reshape_x_2_quant_offset[] = { -128 };
  static const float buff_info_Gemm_13_conv_4_zero_off_out_25_quant_scale[] = { 0.0145292747765779 };
  static const int16_t buff_info_Gemm_13_conv_4_zero_off_out_25_quant_offset[] = { 0 };
  static const uint32_t buff_info__shape_1_5_1_1[] = { 1, 1, 1, 5 };
  static const uint32_t buff_info__mem_shape_F_1_5_1_1[] = { 1, 5, 1, 1 };
  static const float buff_info_Gemm_13_conv_4_off_bias_out_31_quant_scale[] = { 0.0243322141468525 };
  static const int16_t buff_info_Gemm_13_conv_4_off_bias_out_31_quant_offset[] = { 33 };
  static const LL_Buffer_InfoTypeDef buff_info[] = {
    {
      .name = "Conv2D_4_zero_off_out_7",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 256,
      .offset_end = 320,
      .offset_limit = 384,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 1,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_F_1_1_8_8,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 8,
      .Qn = 0,
      .Qunsigned = 1,
      .type = DataType_UINT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_1_8_8,
      .per_channel = 0,
      .scale = buff_info_Conv2D_4_zero_off_out_7_quant_scale,
      .offset = buff_info_Conv2D_4_zero_off_out_7_quant_offset,
    },
    {
      .name = "Conv2D_8_zero_off_out_16",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 0,
      .offset_end = 256,
      .offset_limit = 320,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 2,
      .batch = 8,
      .mem_shape = buff_info__mem_shape_M_1_16_4_4,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 8,
      .Qn = 0,
      .Qunsigned = 1,
      .type = DataType_UINT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_16_4_4,
      .per_channel = 0,
      .scale = buff_info_Conv2D_8_zero_off_out_16_quant_scale,
      .offset = buff_info_Conv2D_8_zero_off_out_16_quant_offset,
    },
    {
      .name = "MaxPool_11_out_0",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 256,
      .offset_end = 384,
      .offset_limit = 448,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 3,
      .batch = 32,
      .mem_shape = buff_info__mem_shape_L_1_32_2_2,
      .mem_ndims = 4,
      .chpos = CHPos_Last,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_32_2_2,
      .per_channel = 0,
      .scale = buff_info_MaxPool_11_out_0_quant_scale,
      .offset = buff_info_MaxPool_11_out_0_quant_offset,
    },
    {
      .name = "Gemm_13_reshape_x_2",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 0,
      .offset_end = 128,
      .offset_limit = 192,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 4,
      .batch = 128,
      .mem_shape = buff_info__mem_shape_F_1_128_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_128_1_1,
      .per_channel = 0,
      .scale = buff_info_Gemm_13_reshape_x_2_quant_scale,
      .offset = buff_info_Gemm_13_reshape_x_2_quant_offset,
    },
    {
      .name = "Gemm_13_conv_4_zero_off_out_25",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 128,
      .offset_end = 256,
      .offset_limit = 320,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 5,
      .batch = 128,
      .mem_shape = buff_info__mem_shape_F_1_128_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 8,
      .Qn = 0,
      .Qunsigned = 1,
      .type = DataType_UINT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_128_1_1,
      .per_channel = 0,
      .scale = buff_info_Gemm_13_conv_4_zero_off_out_25_quant_scale,
      .offset = buff_info_Gemm_13_conv_4_zero_off_out_25_quant_offset,
    },
    {
      .name = "Gemm_13_conv_4_off_bias_out_31",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 0,
      .offset_end = 5,
      .offset_limit = 72,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 6,
      .batch = 5,
      .mem_shape = buff_info__mem_shape_F_1_5_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_5_1_1,
      .per_channel = 0,
      .scale = buff_info_Gemm_13_conv_4_off_bias_out_31_quant_scale,
      .offset = buff_info_Gemm_13_conv_4_off_bias_out_31_quant_offset,
    },
    {
      .name = NULL,
    }
  };

  return buff_info;
}

